baseurl = "https://leechor.github.io/"
languageCode = "en-us"
title = "Licho Space"
theme = "hyde"
copyright = "Licho Space"

[Author]
	name = "Licho Space"

[Permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "code by Licho Space"
	disqus = "licho"
	mainImage = "/moose.svg"

